# Path where the launch module binary can be found (e.g. "launch.so", "launch.dll") relative to the executable directory
launch: .

# Target number of dynamic ticks per second (not a hard constraint)
dynamicTPS: 200

# Window title
title: Cacao Playground

# Working directory relative to the executable directory
workingDir: playground

# Maximum number of frames that the engine can be behind in rendering
maxFrameLag: 2
