# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  ImGui_config = debug
  Glad_config = debug
  CitrusEngine_config = debug
  CitrusPlayground_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  ImGui_config = release
  Glad_config = release
  CitrusEngine_config = release
  CitrusPlayground_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW ImGui Glad CitrusEngine CitrusPlayground

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "Building GLFW - $(GLFW_config)... (1/5)"
	@${MAKE} CXX="zig c++" CC="zig cc" --no-print-directory -C libs/glfw -f Makefile config=$(GLFW_config)
endif

ImGui:
ifneq (,$(ImGui_config))
	@echo "Building ImGui - $(ImGui_config)... (2/5)"
	@${MAKE} CXX="zig c++" CC="zig cc" --no-print-directory -C libs/imgui -f Makefile config=$(ImGui_config)
endif

Glad:
ifneq (,$(Glad_config))
	@echo "Building Glad - $(Glad_config)... (3/5)"
	@${MAKE} CXX="zig c++" CC="zig cc" --no-print-directory -C libs/glad -f Makefile config=$(Glad_config)
endif

CitrusEngine: GLFW Glad ImGui
ifneq (,$(CitrusEngine_config))
	@echo "Building CitrusEngine - $(CitrusEngine_config)... (4/5)"
	@${MAKE} CXX="zig c++" CC="zig cc" --no-print-directory -C CitrusEngine -f Makefile config=$(CitrusEngine_config)
endif

CitrusPlayground: CitrusEngine
ifneq (,$(CitrusPlayground_config))
	@echo "Building CitrusPlayground - $(CitrusPlayground_config)... (5/5)"
	@${MAKE} CXX="zig c++" CC="zig cc" --no-print-directory -C CitrusPlayground -f Makefile config=$(CitrusPlayground_config)
endif

clean:
	@echo "Cleaning all..."
	@${MAKE} CXX="zig c++" CC="zig cc" --no-print-directory -C libs/glfw -f Makefile clean
	@${MAKE} CXX="zig c++" CC="zig cc" --no-print-directory -C libs/imgui -f Makefile clean
	@${MAKE} CXX="zig c++" CC="zig cc" --no-print-directory -C libs/glad -f Makefile clean
	@${MAKE} CXX="zig c++" CC="zig cc" --no-print-directory -C CitrusEngine -f Makefile clean
	@${MAKE} CXX="zig c++" CC="zig cc" --no-print-directory -C CitrusPlayground -f Makefile clean


run-debug:
	@echo "Running..."
	@Build/CitrusPlayground/Debug/x86_64-linux/Binaries/CitrusPlayground

run-release:
	@echo "Running..."
	@Build/CitrusPlayground/Release/x86_64-linux/Binaries/CitrusPlayground

help:
	@echo "Citrus Engine - Powered by GNU Make"
	@echo "==================================="
	@echo "Command usage: make [config=name] [target]"
	@echo ""
	@echo "Available configurations:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "Available targets:"
	@echo "   all (build all, default)"
	@echo "   clean (clean build files)"
	@echo "   run-debug (run Citrus Playground debug build)"
	@echo "   run-release (run Citrus Playground release build)"
	@echo "   GLFW (build GLFW)"
	@echo "   ImGui (build ImGui)"
	@echo "   Glad (build Glad)"
	@echo "   CitrusEngine (build Citrus Engine)"
	@echo "   CitrusPlayground (build Citrus Playground)"
	@echo ""
	@echo "See the GitHub repo here: https://github.com/RobotLeopard86/CitrusEngine"
	@echo "Thank you for contributing to Citrus Engine."