#pragma once

#include <array>
#include <utility>

#include "SDL3/SDL_keycode.h"
#include "SDL3/SDL_mouse.h"

#include "Utilities/Input.hpp"

namespace Cacao {
	constexpr std::array<std::pair<SDL_Keycode, int>, 116> keys = {{{SDLK_A, CACAO_KEY_A},
		{SDLK_B, CACAO_KEY_B},
		{SDLK_C, CACAO_KEY_C},
		{SDLK_D, CACAO_KEY_D},
		{SDLK_E, CACAO_KEY_E},
		{SDLK_F, CACAO_KEY_F},
		{SDLK_G, CACAO_KEY_G},
		{SDLK_H, CACAO_KEY_H},
		{SDLK_I, CACAO_KEY_I},
		{SDLK_J, CACAO_KEY_J},
		{SDLK_K, CACAO_KEY_K},
		{SDLK_L, CACAO_KEY_L},
		{SDLK_M, CACAO_KEY_M},
		{SDLK_N, CACAO_KEY_N},
		{SDLK_O, CACAO_KEY_O},
		{SDLK_P, CACAO_KEY_P},
		{SDLK_Q, CACAO_KEY_Q},
		{SDLK_R, CACAO_KEY_R},
		{SDLK_S, CACAO_KEY_S},
		{SDLK_T, CACAO_KEY_T},
		{SDLK_U, CACAO_KEY_U},
		{SDLK_V, CACAO_KEY_V},
		{SDLK_W, CACAO_KEY_W},
		{SDLK_X, CACAO_KEY_X},
		{SDLK_Y, CACAO_KEY_Y},
		{SDLK_Z, CACAO_KEY_Z},
		{SDLK_0, CACAO_KEY_0},
		{SDLK_1, CACAO_KEY_1},
		{SDLK_2, CACAO_KEY_2},
		{SDLK_3, CACAO_KEY_3},
		{SDLK_4, CACAO_KEY_4},
		{SDLK_5, CACAO_KEY_5},
		{SDLK_6, CACAO_KEY_6},
		{SDLK_7, CACAO_KEY_7},
		{SDLK_8, CACAO_KEY_8},
		{SDLK_9, CACAO_KEY_9},
		{SDLK_SPACE, CACAO_KEY_SPACE},
		{SDLK_SEMICOLON, CACAO_KEY_SEMICOLON},
		{SDLK_EQUALS, CACAO_KEY_EQUAL},
		{SDLK_MINUS, CACAO_KEY_MINUS},
		{SDLK_PERIOD, CACAO_KEY_PERIOD},
		{SDLK_COMMA, CACAO_KEY_COMMA},
		{SDLK_SLASH, CACAO_KEY_SLASH},
		{SDLK_BACKSLASH, CACAO_KEY_BACKSLASH},
		{SDLK_APOSTROPHE, CACAO_KEY_APOSTROPHE},
		{SDLK_GRAVE, CACAO_KEY_GRAVE_ACCENT},
		{SDLK_LEFTBRACKET, CACAO_KEY_LEFT_BRACKET},
		{SDLK_RIGHTBRACKET, CACAO_KEY_RIGHT_BRACKET},
		{SDLK_ESCAPE, CACAO_KEY_ESCAPE},
		{SDLK_RETURN, CACAO_KEY_ENTER},
		{SDLK_TAB, CACAO_KEY_TAB},
		{SDLK_BACKSPACE, CACAO_KEY_BACKSPACE},
		{SDLK_INSERT, CACAO_KEY_INSERT},
		{SDLK_DELETE, CACAO_KEY_DELETE},
		{SDLK_PAGEUP, CACAO_KEY_PAGE_UP},
		{SDLK_PAGEDOWN, CACAO_KEY_PAGE_DOWN},
		{SDLK_HOME, CACAO_KEY_HOME},
		{SDLK_END, CACAO_KEY_END},
		{SDLK_UP, CACAO_KEY_UP},
		{SDLK_DOWN, CACAO_KEY_DOWN},
		{SDLK_LEFT, CACAO_KEY_LEFT},
		{SDLK_RIGHT, CACAO_KEY_RIGHT},
		{SDLK_CAPSLOCK, CACAO_KEY_CAPS_LOCK},
		{SDLK_SCROLLLOCK, CACAO_KEY_SCROLL_LOCK},
		{SDLK_NUMLOCKCLEAR, CACAO_KEY_NUM_LOCK},
		{SDLK_PRINTSCREEN, CACAO_KEY_PRINT_SCREEN},
		{SDLK_F1, CACAO_KEY_F1},
		{SDLK_F2, CACAO_KEY_F2},
		{SDLK_F3, CACAO_KEY_F3},
		{SDLK_F4, CACAO_KEY_F4},
		{SDLK_F5, CACAO_KEY_F5},
		{SDLK_F6, CACAO_KEY_F6},
		{SDLK_F7, CACAO_KEY_F7},
		{SDLK_F8, CACAO_KEY_F8},
		{SDLK_F9, CACAO_KEY_F9},
		{SDLK_F10, CACAO_KEY_F10},
		{SDLK_F11, CACAO_KEY_F11},
		{SDLK_F12, CACAO_KEY_F12},
		{SDLK_F13, CACAO_KEY_F13},
		{SDLK_F14, CACAO_KEY_F14},
		{SDLK_F15, CACAO_KEY_F15},
		{SDLK_F16, CACAO_KEY_F16},
		{SDLK_F17, CACAO_KEY_F17},
		{SDLK_F18, CACAO_KEY_F18},
		{SDLK_F19, CACAO_KEY_F19},
		{SDLK_F20, CACAO_KEY_F20},
		{SDLK_F21, CACAO_KEY_F21},
		{SDLK_F22, CACAO_KEY_F22},
		{SDLK_F23, CACAO_KEY_F23},
		{SDLK_F24, CACAO_KEY_F24},
		{SDLK_LSHIFT, CACAO_KEY_LEFT_SHIFT},
		{SDLK_LALT, CACAO_KEY_LEFT_ALT},
		{SDLK_LCTRL, CACAO_KEY_LEFT_CONTROL},
		{SDLK_LGUI, CACAO_KEY_LEFT_SUPER},
		{SDLK_RSHIFT, CACAO_KEY_RIGHT_SHIFT},
		{SDLK_RALT, CACAO_KEY_RIGHT_ALT},
		{SDLK_RCTRL, CACAO_KEY_RIGHT_CONTROL},
		{SDLK_RGUI, CACAO_KEY_RIGHT_SUPER},
		{SDLK_MENU, CACAO_KEY_MENU},
		{SDLK_KP_0, CACAO_KEY_KP_0},
		{SDLK_KP_1, CACAO_KEY_KP_1},
		{SDLK_KP_2, CACAO_KEY_KP_2},
		{SDLK_KP_3, CACAO_KEY_KP_3},
		{SDLK_KP_4, CACAO_KEY_KP_4},
		{SDLK_KP_5, CACAO_KEY_KP_5},
		{SDLK_KP_6, CACAO_KEY_KP_6},
		{SDLK_KP_7, CACAO_KEY_KP_7},
		{SDLK_KP_8, CACAO_KEY_KP_8},
		{SDLK_KP_9, CACAO_KEY_KP_9},
		{SDLK_KP_PLUS, CACAO_KEY_KP_ADD},
		{SDLK_KP_MINUS, CACAO_KEY_KP_SUBTRACT},
		{SDLK_KP_MULTIPLY, CACAO_KEY_KP_MULTIPLY},
		{SDLK_KP_DIVIDE, CACAO_KEY_KP_DIVIDE},
		{SDLK_KP_DECIMAL, CACAO_KEY_KP_DECIMAL},
		{SDLK_KP_EQUALS, CACAO_KEY_KP_EQUAL},
		{SDLK_KP_ENTER, CACAO_KEY_KP_ENTER}}};

	constexpr std::array<std::pair<Uint8, int>, 8> buttons = {{{SDL_BUTTON_LEFT, CACAO_MOUSE_BUTTON_LEFT},
		{SDL_BUTTON_MIDDLE, CACAO_MOUSE_BUTTON_MIDDLE},
		{SDL_BUTTON_RIGHT, CACAO_MOUSE_BUTTON_RIGHT},
		{SDL_BUTTON_X1, CACAO_MOUSE_BUTTON_4},
		{SDL_BUTTON_X2, CACAO_MOUSE_BUTTON_5},
		{6, CACAO_MOUSE_BUTTON_6},
		{7, CACAO_MOUSE_BUTTON_7},
		{8, CACAO_MOUSE_BUTTON_8}}};

	constexpr int SDLKey2Cacao(SDL_Keycode sdlKeycode) {
		for(const auto& [sdl, cacao] : keys) {
			if(sdl == sdlKeycode) {
				return cacao;
			}
		}
		return -1;
	}

	constexpr int SDLMouseButton2Cacao(Uint8 sdlButton) {
		for(const auto& [sdl, cacao] : buttons) {
			if(sdl == sdlButton) {
				return cacao;
			}
		}
		return -1;
	}
}