import pathlib

# Solution file
print("Writing solution file...")
with open('CacaoEngine.sln', 'w') as sln:
    sln.writelines([
        'Microsoft Visual Studio Solution File, Format Version 12.00\n',
        '# Visual Studio Version 17\n',
        'VisualStudioVersion = 17.10.35013.160\n',
        'MinimumVisualStudioVersion = 10.0.40219.1\n',
        'Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "Cacao", "Cacao.vcxproj", "{A3DB4047-E0C5-4756-B9BB-6CBFCA3B593C}"\n',
        'EndProject\n',
        'Global\n',
	    '    GlobalSection(SolutionConfigurationPlatforms) = preSolution\n',
		'        Debug|x64 = Debug|x64\n',
		'        Release|x64 = Release|x64\n',
	    '    EndGlobalSection\n',
        '    GlobalSection(ProjectConfigurationPlatforms) = postSolution\n',
        '        {A3DB4047-E0C5-4756-B9BB-6CBFCA3B593C}.Debug|x64.ActiveCfg = Debug|x64\n',
        '        {A3DB4047-E0C5-4756-B9BB-6CBFCA3B593C}.Debug|x64.Build.0 = Debug|x64\n',
        '        {A3DB4047-E0C5-4756-B9BB-6CBFCA3B593C}.Release|x64.ActiveCfg = Release|x64\n',
        '        {A3DB4047-E0C5-4756-B9BB-6CBFCA3B593C}.Release|x64.Build.0 = Release|x64\n',
        '    EndGlobalSection\n',
        '    GlobalSection(SolutionProperties) = preSolution\n',
        '        HideSolutionNode = FALSE\n',
        '    EndGlobalSection\n',
        '    GlobalSection(ExtensibilityGlobals) = postSolution\n',
        '        SolutionGuid = {21E313CF-3126-4C3D-A989-CFF684865B94}\n',
        '    EndGlobalSection\n',
        'EndGloba\nl'
    ])

# VCXPROJ file
print("Writing project file...")
with open('Cacao.vcxproj', 'w') as vcx:
    vcx.writelines([
        '<?xml version="1.0" encoding="utf-8"?>\n',
        '<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">\n',
        '  <ItemGroup Label="ProjectConfigurations">\n',
        '    <ProjectConfiguration Include="Debug|x64">\n',
        '      <Configuration>Debug</Configuration>\n',
        '      <Platform>x64</Platform>\n',
        '    </ProjectConfiguration>\n',
        '    <ProjectConfiguration Include="Release|x64">\n',
        '      <Configuration>Release</Configuration>\n',
        '      <Platform>x64</Platform>\n',
        '    </ProjectConfiguration>\n',
        '  </ItemGroup>\n',
        '  <PropertyGroup Label="Globals">\n',
        '    <VCProjectVersion>17.0</VCProjectVersion>\n',
        '    <ProjectGuid>{A3DB4047-E0C5-4756-B9BB-6CBFCA3B593C}</ProjectGuid>\n',
        '    <Keyword>Win32Proj</Keyword>\n',
        '  </PropertyGroup>\n',
        '  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.Default.props" />\n',
        '  <PropertyGroup Condition="\'$(Configuration)|$(Platform)\'==\'Debug|x64\'" Label="Configuration">\n',
        '    <ConfigurationType>Makefile</ConfigurationType>\n',
        '    <UseDebugLibraries>true</UseDebugLibraries>\n',
        '    <PlatformToolset>v143</PlatformToolset>\n',
        '  </PropertyGroup>\n',
        '  <PropertyGroup Condition="\'$(Configuration)|$(Platform)\'==\'Release|x64\'" Label="Configuration">\n',
        '    <ConfigurationType>Makefile</ConfigurationType>\n',
        '    <UseDebugLibraries>false</UseDebugLibraries>\n',
        '    <PlatformToolset>v143</PlatformToolset>\n',
        '  </PropertyGroup>\n',
        '  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.props" />\n',
        '  <ImportGroup Label="ExtensionSettings">\n',
        '  </ImportGroup>\n',
        '  <ImportGroup Label="Shared">\n',
        '  </ImportGroup>\n',
        '  <ImportGroup Label="PropertySheets" Condition="\'$(Configuration)|$(Platform)\'==\'Debug|x64\'">\n',
        '    <Import Project="$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props" Condition="exists(\'$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\')" Label="LocalAppDataPlatform" />\n',
        '  </ImportGroup>\n',
        '  <ImportGroup Label="PropertySheets" Condition="\'$(Configuration)|$(Platform)\'==\'Release|x64\'">\n',
        '    <Import Project="$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props" Condition="exists(\'$(UserRootDir)\\Microsoft.Cpp.$(Platform).user.props\')" Label="LocalAppDataPlatform" />\n',
        '  </ImportGroup>\n',
        '  <PropertyGroup Label="UserMacros" />\n',
        '  <PropertyGroup Condition="\'$(Configuration)|$(Platform)\'==\'Debug|x64\'">\n',
        '    <NMakeBuildCommandLine>meson compile -C $(Configuration) bundle</NMakeBuildCommandLine>\n',
        '    <NMakeOutput>$(Configuration)\\playground.bundled\\cacaoengine.exe</NMakeOutput>\n',
        '    <NMakeCleanCommandLine>meson compile -C $(Configuration) --clean</NMakeCleanCommandLine>\n',
        '    <NMakeReBuildCommandLine>meson compile -C $(Configuration) --clean &amp;&amp; meson compile -C $(Configuration) bundle</NMakeReBuildCommandLine>\n',
        '    <NMakePreprocessorDefinitions>_DEBUG;$(NMakePreprocessorDefinitions)</NMakePreprocessorDefinitions>\n',
        '    <IncludePath>$(VC_IncludePath);$(WindowsSDK_IncludePath);$(ProjectDir)\\cacao\\include;$(ProjectDir)\\backends\\gl-glfw\\include;$(ProjectDir)\\libs\\glm;$(ProjectDir)\\libs\\thread-pool\\include;$(ProjectDir)\\libs\\dr_libs;$(ProjectDir)\\libs\\dynalo\\include;$(ProjectDir)\\libs\\spdlog\\include;$(ProjectDir)\\subprojects\\assimp\\include;$(ProjectDir)\\subprojects\\yaml\\include;$(ProjectDir)\\subprojects\\glad\\include;$(ProjectDir)\\subprojects\\glfw\\include;$(ProjectDir)\\subprojects\\guid\\include;$(ProjectDir)\\subprojects\\openal-soft\\include;$(ProjectDir)\\subprojects\\spirv-cross;$(ProjectDir)\\subprojects\\stb;$(ProjectDir)\\subprojects\\sdl3\\include;$(ProjectDir)\\subprojects\\audiolibs\\ogg\\include;$(ProjectDir)\\subprojects\\audiolibs\\vorbis\\include;$(ProjectDir)\\subprojects\\audiolibs\\opus\\include;$(ProjectDir)\\subprojects\\audiolibs\\opusfile\\include;</IncludePath>\n',
        '  </PropertyGroup>\n',
        '  <PropertyGroup Condition="\'$(Configuration)|$(Platform)\'==\'Release|x64\'">\n',
        '    <NMakeBuildCommandLine>meson compile -C $(Configuration) playground</NMakeBuildCommandLine>\n',
        '    <NMakeOutput>$(Configuration)\\playground.bundled\\cacaoengine.exe</NMakeOutput>\n',
        '    <NMakeCleanCommandLine>meson compile -C $(Configuration) --clean</NMakeCleanCommandLine>\n',
        '    <NMakeReBuildCommandLine>meson compile -C $(Configuration) --clean &amp;&amp; meson compile -C $(Configuration) bundle</NMakeReBuildCommandLine>\n',
        '    <NMakePreprocessorDefinitions>_DEBUG;$(NMakePreprocessorDefinitions)</NMakePreprocessorDefinitions>\n',
        '    <IncludePath>$(VC_IncludePath);$(WindowsSDK_IncludePath);$(ProjectDir)\\cacao\\include;$(ProjectDir)\\backends\\gl-glfw\\include;$(ProjectDir)\\libs\\glm;$(ProjectDir)\\libs\\thread-pool\\include;$(ProjectDir)\\libs\\dr_libs;$(ProjectDir)\\libs\\dynalo\\include;$(ProjectDir)\\libs\\spdlog\\include;$(ProjectDir)\\subprojects\\assimp\\include;$(ProjectDir)\\subprojects\\yaml\\include;$(ProjectDir)\\subprojects\\glad\\include;$(ProjectDir)\\subprojects\\glfw\\include;$(ProjectDir)\\subprojects\\guid\\include;$(ProjectDir)\\subprojects\\openal-soft\\include;$(ProjectDir)\\subprojects\\spirv-cross;$(ProjectDir)\\subprojects\\stb;$(ProjectDir)\\subprojects\\sdl3\\include;$(ProjectDir)\\subprojects\\audiolibs\\ogg\\include;$(ProjectDir)\\subprojects\\audiolibs\\vorbis\\include;$(ProjectDir)\\subprojects\\audiolibs\\opus\\include;$(ProjectDir)\\subprojects\\audiolibs\\opusfile\\include;</IncludePath>\n',
        '  </PropertyGroup>\n',
        '  <ItemDefinitionGroup>\n',
        '  </ItemDefinitionGroup>\n',
        '  <ItemGroup>\n',
        '    <None Include=".clang-format" />\n',
        '    <None Include=".clang-format-ignore" />\n',
        '    <None Include=".gitignore" />\n',
        '    <None Include=".gitmodules" />\n',
        '    <None Include="BACKENDS.md" />\n',
        '    <None Include="BUILD.md" />\n',
        '    <None Include="default_native.ini" />\n',
        '    <None Include="LICENSE" />\n',
        '    <None Include="meson.build" />\n',
        '    <None Include="meson.options" />\n',
        '    <None Include="playground\\src\\shaders\\ico.frag" />\n',
        '    <None Include="playground\\src\\shaders\\ico.vert" />\n',
        '    <None Include="playground\\src\\shaders\\prism.frag" />\n',
        '    <None Include="playground\\src\\shaders\\prism.vert" />\n',
        '    <None Include="README.md" />\n',
        '  </ItemGroup>\n',
        '  <ItemGroup>\n',
        '    <Image Include="cacaologo.png" />\n',
        '  </ItemGroup>\n',
        '  <ItemGroup>\n',
        '    <ClInclude Include="backends\\gl-glfw\\include\\GLCubemapData.hpp" />\n',
        '    <ClInclude Include="backends\\gl-glfw\\include\\GLMeshData.hpp" />\n',
        '    <ClInclude Include="backends\\gl-glfw\\include\\GLShaderData.hpp" />\n',
        '    <ClInclude Include="backends\\gl-glfw\\include\\GLSkyboxData.hpp" />\n',
        '    <ClInclude Include="backends\\gl-glfw\\include\\GLTexture2DData.hpp" />\n',
        '    <ClInclude Include="backends\\gl-glfw\\include\\GLUtils.hpp" />\n',
        '    <ClInclude Include="backends\\gl-sdl\\include\\GLCubemapData.hpp" />\n',
        '    <ClInclude Include="backends\\gl-sdl\\include\\GLMeshData.hpp" />\n',
        '    <ClInclude Include="backends\\gl-sdl\\include\\GLShaderData.hpp" />\n',
        '    <ClInclude Include="backends\\gl-sdl\\include\\GLSkyboxData.hpp" />\n',
        '    <ClInclude Include="backends\\gl-sdl\\include\\GLTexture2DData.hpp" />\n',
        '    <ClInclude Include="backends\\gl-sdl\\include\\GLUtils.hpp" />\n',
        '    <ClInclude Include="backends\\gl-sdl\\include\\KeyAndMouseLUT.hpp" />\n',
        '    <ClInclude Include="backends\\gl-sdl\\include\\SDLWindowData.hpp" />\n',
        '    <ClInclude Include="backends\\gles-glfw\\include\\ESCubemapData.hpp" />\n',
        '    <ClInclude Include="backends\\gles-glfw\\include\\ESMeshData.hpp" />\n',
        '    <ClInclude Include="backends\\gles-glfw\\include\\ESShaderData.hpp" />\n',
        '    <ClInclude Include="backends\\gles-glfw\\include\\ESSkyboxData.hpp" />\n',
        '    <ClInclude Include="backends\\gles-glfw\\include\\ESTexture2DData.hpp" />\n',
        '    <ClInclude Include="backends\\gles-glfw\\include\\ESUtils.hpp" />\n',
        '    <ClInclude Include="backends\\gles-sdl\\include\\ESCubemapData.hpp" />\n',
        '    <ClInclude Include="backends\\gles-sdl\\include\\ESMeshData.hpp" />\n',
        '    <ClInclude Include="backends\\gles-sdl\\include\\ESShaderData.hpp" />\n',
        '    <ClInclude Include="backends\\gles-sdl\\include\\ESSkyboxData.hpp" />\n',
        '    <ClInclude Include="backends\\gles-sdl\\include\\ESTexture2DData.hpp" />\n',
        '    <ClInclude Include="backends\\gles-sdl\\include\\ESUtils.hpp" />\n',
        '    <ClInclude Include="backends\\gles-sdl\\include\\KeyAndMouseLUT.hpp" />\n',
        '    <ClInclude Include="backends\\gles-sdl\\include\\SDLWindowData.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\3D\\Mesh.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\3D\\Model.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\3D\\Skybox.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\3D\\Transform.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\3D\\Vertex.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Audio\\AudioPlayer.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Audio\\AudioSystem.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Audio\\Sound.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Cacao.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Core\\Assert.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Core\\DynTickController.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Core\\Engine.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Core\\EngineConfig.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Core\\Exception.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Core\\Log.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Events\\Event.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Events\\EventConsumer.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Events\\EventManager.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Events\\EventSystem.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Graphics\\Cameras\\Camera.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Graphics\\Cameras\\PerspectiveCamera.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Graphics\\Material.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Graphics\\Rendering\\MeshComponent.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Graphics\\Rendering\\RenderController.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Graphics\\Rendering\\RenderObjects.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Graphics\\Shader.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Graphics\\Textures\\Cubemap.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Graphics\\Textures\\Texture.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Graphics\\Textures\\Texture2D.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Graphics\\Window.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Scripts\\Script.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Utilities\\Asset.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Utilities\\AssetManager.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Utilities\\Flushable.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Utilities\\Input.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Utilities\\MiscUtils.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Utilities\\MultiFuture.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\Utilities\\Task.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\World\\Component.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\World\\Entity.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\World\\World.hpp" />\n',
        '    <ClInclude Include="cacao\\include\\World\\WorldManager.hpp" />\n',
        '  </ItemGroup>\n',
        '  <ItemGroup>\n',
        '    <ClCompile Include="backends\\gl-glfw\\src\\Cubemap.cpp" />\n',
        '    <ClCompile Include="backends\\gl-glfw\\src\\ExceptionCodes.cpp" />\n',
        '    <ClCompile Include="backends\\gl-glfw\\src\\Mesh.cpp" />\n',
        '    <ClCompile Include="backends\\gl-glfw\\src\\OpenGL.cpp" />\n',
        '    <ClCompile Include="backends\\gl-glfw\\src\\Shader.cpp" />\n',
        '    <ClCompile Include="backends\\gl-glfw\\src\\Skybox.cpp" />\n',
        '    <ClCompile Include="backends\\gl-glfw\\src\\Texture2D.cpp" />\n',
        '    <ClCompile Include="backends\\gl-glfw\\src\\Window.cpp" />\n',
        '    <ClCompile Include="backends\\gl-sdl\\src\\Cubemap.cpp" />\n',
        '    <ClCompile Include="backends\\gl-sdl\\src\\ExceptionCodes.cpp" />\n',
        '    <ClCompile Include="backends\\gl-sdl\\src\\Mesh.cpp" />\n',
        '    <ClCompile Include="backends\\gl-sdl\\src\\OpenGL.cpp" />\n',
        '    <ClCompile Include="backends\\gl-sdl\\src\\Shader.cpp" />\n',
        '    <ClCompile Include="backends\\gl-sdl\\src\\Skybox.cpp" />\n',
        '    <ClCompile Include="backends\\gl-sdl\\src\\Texture2D.cpp" />\n',
        '    <ClCompile Include="backends\\gl-sdl\\src\\Window.cpp" />\n',
        '    <ClCompile Include="backends\\gles-glfw\\src\\Cubemap.cpp" />\n',
        '    <ClCompile Include="backends\\gles-glfw\\src\\ExceptionCodes.cpp" />\n',
        '    <ClCompile Include="backends\\gles-glfw\\src\\GLES.cpp" />\n',
        '    <ClCompile Include="backends\\gles-glfw\\src\\Mesh.cpp" />\n',
        '    <ClCompile Include="backends\\gles-glfw\\src\\Shader.cpp" />\n',
        '    <ClCompile Include="backends\\gles-glfw\\src\\Skybox.cpp" />\n',
        '    <ClCompile Include="backends\\gles-glfw\\src\\Texture2D.cpp" />\n',
        '    <ClCompile Include="backends\\gles-glfw\\src\\Window.cpp" />\n',
        '    <ClCompile Include="backends\\gles-sdl\\src\\Cubemap.cpp" />\n',
        '    <ClCompile Include="backends\\gles-sdl\\src\\ExceptionCodes.cpp" />\n',
        '    <ClCompile Include="backends\\gles-sdl\\src\\GLES.cpp" />\n',
        '    <ClCompile Include="backends\\gles-sdl\\src\\Mesh.cpp" />\n',
        '    <ClCompile Include="backends\\gles-sdl\\src\\Shader.cpp" />\n',
        '    <ClCompile Include="backends\\gles-sdl\\src\\Skybox.cpp" />\n',
        '    <ClCompile Include="backends\\gles-sdl\\src\\Texture2D.cpp" />\n',
        '    <ClCompile Include="backends\\gles-sdl\\src\\Window.cpp" />\n',
        '    <ClCompile Include="cacao\\expf.c" />\n',
        '    <ClCompile Include="cacao\\src\\3D\\Model.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\3D\\Transform.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\Audio\\AudioPlayer.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\Audio\\AudioSystem.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\Audio\\Sound.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\Cameras\\PerspectiveCamera.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\Core\\Assert.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\Core\\DynTickController.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\Core\\Engine.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\Core\\Log.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\Core\\Startup.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\Events\\EventManager.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\Rendering\\RenderController.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\Utilities\\AssetManager.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\Utilities\\Input.cpp" />\n',
        '    <ClCompile Include="cacao\\src\\World\\WorldManager.cpp" />\n',
        '    <ClCompile Include="playground\\src\\Playground.cpp" />\n',
        '  </ItemGroup>\n',
        '  <Import Project="$(VCTargetsPath)\\Microsoft.Cpp.targets" />\n',
        '  <ImportGroup Label="ExtensionTargets">\n',
        '  </ImportGroup>\n',
        '</Project>\n',
    ])

print('Complete.')