#pragma once

//The collection of shaders for UI elements
//Shader code generated by glslc at build-time

#include "Graphics/Shader.hpp"

namespace Cacao {
	//Backend-implemented
	void GenShaders();

	//Clean up shaders
	void DelShaders();

	namespace TextShaders {
		static constexpr uint32_t vertex[] =
#include "text.vert.txt"
			;
		static constexpr uint32_t fragment[] =
#include "text.frag.txt"
			;
		static Shader* shader;
	}
}