name: Update docs on main update

permissions: write-all

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Doxygen
        run: |
          sudo apt-get update;
          sudo apt-get install doxygen -y
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch thread pool project for docs
        run: |
          git clone https://github.com/DeveloperPaul123/thread-pool subprojects/thread-pool
          git -C subprojects/thread-pool checkout 0.6.2
      - name: Build documentation
        uses: sphinx-notes/pages@v2
        with:
          sphinx_options: "-j auto -a"
          target_path: main
          target_branch: gh-pages
          sphinx_version: "7.3.7"
          requirements_path: "docs/requirements.txt"
          documentation_path: "docs"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
